;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/MoreSwatchSlots/Content/Localization/MoreSwatchSlots
DestinationPath=Mods/MoreSwatchSlots/Content/Localization/MoreSwatchSlots
ManifestName=MoreSwatchSlots.manifest
ArchiveName=MoreSwatchSlots.archive
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=fr-FR
CulturesToGenerate=ko-KR
CulturesToGenerate=pt-BR
CulturesToGenerate=ru-RU
CulturesToGenerate=zh-TW

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=%LOCPROJECTROOT%Mods/MoreSwatchSlots/Config
ExcludePathFilters=Config/Localization/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=%LOCPROJECTROOT%Mods/MoreSwatchSlots/Content/*
ExcludePathFilters=Content/Localization/*
ExcludePathFilters=Content/L10N/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
ExcludeClasses=/Script/Engine.MaterialInstance
ExcludeClasses=/Script/Engine.Material
ExcludeClasses=/Script/Engine.StaticMesh
ExcludeClasses=/Script/Engine.SkeletalMesh
ExcludeClasses=/Script/Engine.Texture
ExcludeClasses=/Script/Engine.MaterialFunction
ShouldExcludeDerivedClasses=true
ShouldGatherFromEditorOnlyData=false
SkipGatherCache=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive

[GatherTextStep4]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=MoreSwatchSlots.csv
bConflictReport=true
ConflictReportName=MoreSwatchSlots_Conflicts.txt

