;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/MoreSwatchSlots/Content/Localization/MoreSwatchSlots
DestinationPath=Mods/MoreSwatchSlots/Content/Localization/MoreSwatchSlots
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=fr-FR
CulturesToGenerate=ko-KR
CulturesToGenerate=pt-BR
CulturesToGenerate=ru-RU
CulturesToGenerate=zh-TW
ManifestName=MoreSwatchSlots.manifest
ArchiveName=MoreSwatchSlots.archive
PortableObjectName=MoreSwatchSlots.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Unreal

