;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/SBS/Content/Localization/SBS
DestinationPath=Mods/GameFeatures/SBS/Content/Localization/SBS
ManifestName=SBS.manifest
ArchiveName=SBS.archive
ResourceName=SBS.locres
NativeCulture=en
CulturesToGenerate=en
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource
