// Copyright Kyri123 / KMods 2026. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

#include "NativeGameplayTags.h"

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_ExcludeFromNodeRandomization);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_Disabled);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_DeliveryGateUnlock);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_AlternateRecipe);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_PlannerExclude);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_PlannerExcludeOverclocking);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_PlannerRawRecipe);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_PlannerResource);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_MinerModuleCrusher);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_MinerModuleSmelter);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_MinerModuleFluid);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_WikiExclude);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_Deprecated);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_WIP);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_Cheat);

KAPI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KMods_EventOnly);
