#include "KBFLLogging.h"

DEFINE_LOG_CATEGORY(KBFLMenuModuleLog);
DEFINE_LOG_CATEGORY(KBFLGameInstanceModuleLog);
DEFINE_LOG_CATEGORY(ContentCDOHelperSubsystem);
DEFINE_LOG_CATEGORY(KBFLInstanceSpawnerLog);
DEFINE_LOG_CATEGORY(AssetDataSubsystemLog);
DEFINE_LOG_CATEGORY(KBFLWorldModuleLog);
DEFINE_LOG_CATEGORY(KBFLAssetLog);
DEFINE_LOG_CATEGORY(LogKBFLModule);
DEFINE_LOG_CATEGORY(KBFLActorSpawnerLog);
DEFINE_LOG_CATEGORY(KBFLSubLevelSpawnerLog);
DEFINE_LOG_CATEGORY(CustomizerSubsystem);
