[AccessTransformers]
Friend = (Class="AFGResourceNode", FriendClass="AKLMMBuildableBase")
Friend = (Class="AFGBuildableResourceExtractor", FriendClass="AKLMMBuildableBase")
Friend = (Class="AFGBuildableResourceExtractorBase", FriendClass="AKLMMBuildableBase")
Friend = (Class="AFGBuildableResourceExtractor", FriendClass="AKLMMBuildableMiner")
Friend = (Class="AFGBuildableResourceExtractorBase", FriendClass="AKLMMBuildableMiner")
Friend = (Class="AFGBuildableResourceExtractor", FriendClass="AKLBuildableResourceExtractorCons")
Friend = (Class="UFGProductionIndicatorInstanceComponent", FriendClass="AKLBuildableSlugHatching")
Friend = (Class="AFGBuildableSubsystem", FriendClass="AKLBuildableSlugHatching")
Friend = (Class="AFGRecipeManager", FriendClass="UUKLUnlockCleanerItem")
Friend = (Class="UFGGameUserSettings", FriendClass="AKLAirCollectorHologram")
Friend = (Class="AFGBuildable", FriendClass="UKLGameInstance")
Friend = (Class="AAbstractInstanceManager", FriendClass="UKLGameInstance")
Friend = (Class="AFGCentralStorageContainer", FriendClass="AKLDepotSinkStorage")
Friend = (Class="AFGTutorialIntroManager", FriendClass="UKLGiveItemToAllPlayerUnlock")
; Custom FGIconLibrary
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="ID")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="IconType")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="ItemDescriptor")
EditAnywhere=(Class="/Script/FactoryGame.IconData", Property="DisplayNameOverride")

EditAnywhere=(Class="UFGIconLibrary", Property="mMapStampIconData")
EditAnywhere=(Class="UFGIconLibrary", Property="mMaterialIconData")
EditAnywhere=(Class="UFGIconLibrary", Property="mCustomIconData")
EditAnywhere=(Class="UFGIconLibrary", Property="mMonochromeIconData")
EditAnywhere=(Class="UFGIconLibrary", Property="mIconData")

Friend = (Class="AFGGasPillar", FriendClass="AKLToxicResourceNode")
Friend = (Class="AFGGasPillarCloud", FriendClass="AKLToxicResourceNode")
