#pragma once

#include "CoreMinimal.h"

DECLARE_LOG_CATEGORY_EXTERN(LogKLIB, Log, All)

DECLARE_LOG_CATEGORY_EXTERN(LogKLIB_Modular, Log, All)

DECLARE_LOG_CATEGORY_EXTERN(LogKLIB_Inventory, Log, All)

DECLARE_LOG_CATEGORY_EXTERN(LogKLIB_Components, Log, All)

DECLARE_LOG_CATEGORY_EXTERN(LogKLIB_Production, Log, All)

DECLARE_LOG_CATEGORY_EXTERN(LogKLIB_Extractor, Log, All)

DECLARE_LOG_CATEGORY_EXTERN(LogKLIB_Hologram, Log, All)

DECLARE_LOG_CATEGORY_EXTERN(LogKLIB_InventoryReplication, Log, All)
