;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/KLib/Content/Localization/KLib
DestinationPath=Mods/GameFeatures/KLib/Content/Localization/KLib
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de-DE
CulturesToGenerate=ko-KR
CulturesToGenerate=ru-RU
CulturesToGenerate=zh-TW
ManifestName=KLib.manifest
ArchiveName=KLib.archive
PortableObjectName=KLib.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Unreal

