;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/KPrivateCodeLib/Content/Localization/KPrivateCodeLib
DestinationPath=Mods/GameFeatures/KPrivateCodeLib/Content/Localization/KPrivateCodeLib
ManifestName=KPrivateCodeLib.manifest
ArchiveName=KPrivateCodeLib.archive
ResourceName=KPrivateCodeLib.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=fr-FR
CulturesToGenerate=ko-KR
CulturesToGenerate=pt-BR
CulturesToGenerate=ru-RU
CulturesToGenerate=zh-TW

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

