;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/KUI/Content/Localization/KUI
DestinationPath=Mods/GameFeatures/KUI/Content/Localization/KUI
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=fr-FR
CulturesToGenerate=ko-KR
CulturesToGenerate=zh-TW
ManifestName=KUI.manifest
ArchiveName=KUI.archive
PortableObjectName=KUI.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Unreal

