;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/RSS/Content/Localization/RSS
DestinationPath=Mods/GameFeatures/RSS/Content/Localization/RSS
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de-DE
CulturesToGenerate=ru-RU
ManifestName=RSS.manifest
ArchiveName=RSS.archive
PortableObjectName=RSS.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Unreal

