;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/RSS/Content/Localization/RSS
DestinationPath=Mods/RSS/Content/Localization/RSS
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de-DE
ManifestName=RSS.manifest
ArchiveName=RSS.archive
PortableObjectName=RSS.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bExportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Unreal
ShouldPersistCommentsOnExport=false
ShouldAddSourceLocationsAsComments=true

