;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/RSS/Content/Localization/RSS
DestinationPath=Mods/GameFeatures/RSS/Content/Localization/RSS
ManifestName=RSS.manifest
ArchiveName=RSS.archive
ResourceName=RSS.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de-DE
CulturesToGenerate=ru-RU

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

