;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
ModulesToPreload=RSS
SourcePath=Mods/GameFeatures/RSS/Content/Localization/RSS
DestinationPath=Mods/GameFeatures/RSS/Content/Localization/RSS
ManifestName=RSS.manifest
ArchiveName=RSS.archive
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de-DE
CulturesToGenerate=ru-RU

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=%LOCPROJECTROOT%Mods/GameFeatures/RSS/Source
SearchDirectoryPaths=%LOCPROJECTROOT%Mods/GameFeatures/RSS/Config
ExcludePathFilters=Config/Localization/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=%LOCPROJECTROOT%Mods/GameFeatures/RSS/Content/*
ExcludePathFilters=Content/Localization/*
ExcludePathFilters=Content/L10N/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
ExcludeClasses=/Script/Engine.MaterialInstance
ExcludeClasses=/Script/Engine.Material
ExcludeClasses=/Script/Engine.StaticMesh
ExcludeClasses=/Script/Engine.SkeletalMesh
ExcludeClasses=/Script/Engine.Texture
ExcludeClasses=/Script/Engine.MaterialFunction
ShouldExcludeDerivedClasses=true
ShouldGatherFromEditorOnlyData=false
SkipGatherCache=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive

[GatherTextStep4]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=RSS.csv
bConflictReport=true
ConflictReportName=RSS_Conflicts.txt

