[AccessTransformers]
BlueprintReadWrite = (Class="/Script/FactoryGame.FGFactoryBuildingHologram", Property="mMaxZoopAmount")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGFactoryCustomizationCollection", Property="mCustomizations")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableSubsystem", Property="mCustomizationCollectionClasses")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGResearchTree", Property="mNodes")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGGameState", Property="mSwatchGroupDatum")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildablePowerStorage", Property="mPowerStoreCapacity")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildablePowerStorage", Property="mPowerInputCapacity")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableGeneratorFuel", Property="mAvailableFuelClasses")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableGeneratorFuel", Property="mCurrentFuelClass")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableGeneratorFuel", Property="mSupplementalResourceClass")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableGeneratorFuel", Property="mDefaultFuelClasses")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGItemDescriptor", Property="mSubCategories")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGItemDescriptor", Property="mQuickSwitchGroup")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGItemDescriptor", Property="mMenuPriority")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGItemDescriptor", Property="mCategory")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGItemDescriptor", Property="mGameplayTags")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mStep1UpgradeSchematic")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mStep1_5UpgradeSchematic")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mStep2UpgradeSchematic")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mStep3UpgradeSchematic")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mStep4UpgradeSchematic")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mStep5UpgradeSchematic")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mDidStep1Upgrade")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mDidStep1_5Upgrade")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mDidStep2Upgrade")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mDidStep3Upgrade")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mDidStep4Upgrade")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mDidStep5Upgrade")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mIronOreDescriptor")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mHasCompletedIntroSequence")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGTutorialIntroManager", Property="mHasCompletedIntroTutorial")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGPlayerSettings", Property="mRecipesToGivePlayersPerTier")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGGameState", Property="mUnlockCustomizerSchematic")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGPoolSettings", Property="PoolEntry")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableResourceExtractorBase", Property="mExtractResourceNode")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableResourceExtractorBase", Property="mExtractableResource")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildablePipeline", Property="mRadius")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildablePipeline", Property="mFlowLimit")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableResourceExtractor", Property="mExtractCycleTime")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableResourceExtractor", Property="mItemsPerCycle")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGRecipe", Property="mGameplayTags")

Friend = (Class="UFGSchematic", FriendClass="UKBFL_Asset")
Friend = (Class="UFGItemDescriptor", FriendClass="UKBFL_Asset")
Friend = (Class="UFGRecipe", FriendClass="UKBFL_Asset")
Friend = (Class="AFGBuildable", FriendClass="UKBFLEditorSubsystem")

Friend = (Class="AFGBuildable", FriendClass="AKBFLInstanceWorldActorSubsystem")

Friend = (Class="UFGRecipe", FriendClass="AKBFLDataSubsystem")
Friend = (Class="UFGSchematic", FriendClass="AKBFLDataSubsystem")
Friend = (Class="UFGItemDescriptor", FriendClass="AKBFLDataSubsystem")
Friend = (Class="AFGUnlockSubsystem", FriendClass="UKBFL_Util")
Friend = (Class="AFGBuildGun", FriendClass="UKBFL_Player")

Friend = (Class="UWorldModuleManager", FriendClass="UKBFLResourceNodeSubsystem")
Friend = (Class="AFGResourceNode", FriendClass="UKBFLResourceNodeSubsystem")
Friend = (Class="AFGResourceNodeBase", FriendClass="UKBFLResourceNodeSubsystem")
Friend = (Class="AFGResourceScanner", FriendClass="UKBFLResourceNodeSubsystem")
Friend = (Class="AFGResourceNodeFrackingCore", FriendClass="UKBFLResourceNodeSubsystem")
Friend = (Class="AFGResourceNodeFrackingSatellite", FriendClass="UKBFLResourceNodeSubsystem")

Friend = (Class="UWorldModuleManager", FriendClass="UKBFLContentCDOHelperSubsystem")
Friend = (Class="UFGItemDescriptor", FriendClass="UKBFLContentCDOHelperSubsystem")
Friend = (Class="UFGItemDescriptorNuclearFuel", FriendClass="UKBFLContentCDOHelperSubsystem")
Friend = (Class="UFGResourceDescriptor", FriendClass="UKBFLContentCDOHelperSubsystem")
Friend = (Class="UFGSchematic", FriendClass="UKBFLContentCDOHelperSubsystem")
Friend = (Class="UModContentRegistry", FriendClass="UKBFLContentCDOHelperSubsystem")

Friend = (Class="AFGResourceNode", FriendClass="UKBFLResourceNodeDescriptor")
Friend = (Class="AFGResourceNodeBase", FriendClass="UKBFLResourceNodeDescriptor")
Friend = (Class="AFGResourceNodeFrackingCore", FriendClass="UKBFLResourceNodeDescriptor")
Friend = (Class="AFGResourceNodeFrackingSatellite", FriendClass="UKBFLResourceNodeDescriptor")

Friend = (Class="AFGResourceNode", FriendClass="UKBFLResourceNodeDescriptor_ResourceNode")
Friend = (Class="AFGResourceNodeBase", FriendClass="UKBFLResourceNodeDescriptor_ResourceNode")
Friend = (Class="AFGResourceNodeFrackingCore", FriendClass="UKBFLResourceNodeDescriptor_ResourceNode")
Friend = (Class="AFGResourceNodeFrackingSatellite", FriendClass="UKBFLResourceNodeDescriptor_ResourceNode")
Friend = (Class="AFGBuildableResourceExtractorBase", FriendClass="UKBFLResourceNodeDescriptor_ResourceNode")

Friend = (Class="AFGResourceNode", FriendClass="UKBFLResourceNodeDescriptor_ResourceWell")
Friend = (Class="AFGResourceNodeBase", FriendClass="UKBFLResourceNodeDescriptor_ResourceWell")
Friend = (Class="AFGResourceNodeFrackingCore", FriendClass="UKBFLResourceNodeDescriptor_ResourceWell")
Friend = (Class="AFGResourceNodeFrackingSatellite", FriendClass="UKBFLResourceNodeDescriptor_ResourceWell")
Friend = (Class="AFGBuildableFrackingActivator", FriendClass="UKBFLResourceNodeDescriptor_ResourceWell")
Friend = (Class="AFGBuildableResourceExtractorBase", FriendClass="UKBFLResourceNodeDescriptor_ResourceWell")

Friend = (Class="AFGBuildableFrackingActivator", FriendClass="FKBFLModule")
Friend = (Class="AFGBuildableFrackingExtractor", FriendClass="FKBFLModule")
Friend = (Class="UWorldModuleManager", FriendClass="FKBFLModule")
Friend = (Class="UFGPoolSettings", FriendClass="UKBFLWorldModule")
Friend = (Class="UFGPipeConnectionFactory", FriendClass="AKBFLUtilItemCreaterBuildable")
Friend = (Class="USubsystemActorManager", FriendClass="UKBFL_Util")
Friend = (Class="AFGCharacterPlayer", FriendClass="FKBFLModule")
Friend = (Class="AFGResearchManager", FriendClass="AKBFLUtilSubsystem")
Friend = (Class="AFGCreatureSpawner", FriendClass="UKBFLSpawnerDescriptor")
Friend = (Class="AFGBuildableWire", FriendClass="FKBFLModule")
Friend = (Class="UFGRecipe", FriendClass="UKBFLContentCDOHelperSubsystem")
Friend = (Class="UFGSaveSession", FriendClass="UKBFLSubLevelSpawning")
Friend = (Class="AFGWorldSettings", FriendClass="UKBFLSubLevelSpawning")

Friend = (Class="UFGItemDescriptor", FriendClass="UKBFLCustomizerSubsystem")
Friend = (Class="AFGGameState", FriendClass="UKBFLCustomizerSubsystem")
Friend = (Class="AFGBuildableSubsystem", FriendClass="UKBFLCustomizerSubsystem")
Friend = (Class="UFGFactoryCustomizationCollection", FriendClass="UKBFLCustomizerSubsystem")
Friend = (Class="UWorldModuleManager", FriendClass="UKBFLCustomizerSubsystem")
Friend = (Class="UFGFactoryCustomizationDescriptor_Material", FriendClass="UKBFLCustomizerSubsystem")
Friend = (Class="UFGFactoryCustomizationDescriptor", FriendClass="UKBFLCustomizerSubsystem")
Friend = (Class="UFGItemDescriptor", FriendClass="UKBFLCustomizerSubsystem")

Friend = (Class="UFGItemDescriptor", FriendClass="AKBFLSwatchReplicationSubsystem")
Friend = (Class="AFGGameState", FriendClass="AKBFLSwatchReplicationSubsystem")
Friend = (Class="AFGBuildableSubsystem", FriendClass="AKBFLSwatchReplicationSubsystem")
Friend = (Class="UFGFactoryCustomizationCollection", FriendClass="AKBFLSwatchReplicationSubsystem")
Friend = (Class="UWorldModuleManager", FriendClass="AKBFLSwatchReplicationSubsystem")
Friend = (Class="UFGFactoryCustomizationDescriptor_Material", FriendClass="AKBFLSwatchReplicationSubsystem")
Friend = (Class="UFGFactoryCustomizationDescriptor", FriendClass="AKBFLSwatchReplicationSubsystem")
Friend = (Class="UFGItemDescriptor", FriendClass="AKBFLSwatchReplicationSubsystem")
Friend = (Class="AFGBuildable", FriendClass="AKBFLSwatchReplicationSubsystem")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGResourceSinkSubsystem", Property="mCachedResourceSinkPoints")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGRecipe", Property="mDisplayNameOverride")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGRecipe", Property="mOverriddenCategory")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGRecipe", Property="mManufacturingMenuPriority")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGRecipe", Property="mManufactoringDuration")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGRecipe", Property="mManualManufacturingMultiplier")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGRecipe", Property="mProducedIn")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGRecipe", Property="mMaterialCustomizationRecipe")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGRecipe", Property="mRelevantEvents")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableConveyorBase", Property="mSpeed")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableManufacturer", Property="mManufacturingSpeed")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildableManufacturer", Property="mFluidStackSizeMultiplier")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildable", Property="mDisplayName")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildable", Property="mDescription")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGHealthComponent", Property="mDamageTypeModifiers")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGHealthComponent", Property="mMaxHealth")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGHealthComponent", Property="mCurrentHealth")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGHealthComponent", Property="mRespawnHealthFactor")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGHealthComponent", Property="mIsDead")

BlueprintReadWrite = (Class="/Script/FactoryGame.FGResourceSettings", Property="mResourceDepositTable")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGResourceSettings", Property="mResourceAmount")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGResourceSettings", Property="mPurityMultiplier")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGResourceSettings", Property="mStackSizes")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGResourceSettings", Property="mItemDropClass")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGResourceSettings", Property="mGeyserPowerOutputCurves")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGResourceSettings", Property="mDefaultItemMesh")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGResourceSettings", Property="mGeyserPowerOutputCurves")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGBuildablePipeline", Property="mFlowIndicatorClass")
BlueprintReadWrite = (Class="/Script/FactoryGame.FGItemPickup", Property="mPickupItems")
Friend = (Class="UModContentRegistry", FriendClass="UKBFLWorldModule")

# ------------ New CDO
Friend = (Class="UFGCategory", FriendClass="UKBFLCDOCategoryOrder")

Friend = (Class="UFGItemDescriptor", FriendClass="UKBFLCDOItemStackSize")

Friend = (Class="UFGItemDescriptor", FriendClass="UKBFLCDOCategoryOrder")
Friend = (Class="UFGItemDescriptor", FriendClass="UKBFLCDOCategoryOverwrite")

Friend = (Class="AFGResearchManager", FriendClass="UKBFLWorldCDOContentRemover")

Friend = (Class="AFGRecipeManager", FriendClass="UKBFLWorldCDOContentRemover")

Friend = (Class="AFGSchematicManager", FriendClass="UKBFLWorldCDOContentRemover")

Friend = (Class="UFGRecipe", FriendClass="UKBFLCDOCategoryOverwrite")
Friend = (Class="UFGRecipe", FriendClass="UKBFLCDORecipeMover")
Friend = (Class="UFGRecipe", FriendClass="UKBFLCDOOverwrite")
# ------------ End New CDO
