;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/KBlueprintDesignPlus/Content/Localization/KBlueprintDesignPlus
DestinationPath=Mods/GameFeatures/KBlueprintDesignPlus/Content/Localization/KBlueprintDesignPlus
NativeCulture=en
CulturesToGenerate=en
ManifestName=KBlueprintDesignPlus.manifest
ArchiveName=KBlueprintDesignPlus.archive
PortableObjectName=KBlueprintDesignPlus.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Crowdin

