#pragma once

#include "CoreMinimal.h"

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(KBFLInstanceSpawnerLog, Log, All);

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(KBFLActorSpawnerLog, Log, All);

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(KBFLSubLevelSpawnerLog, Log, All);

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(LogKBFLModule, Log, All);

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(KBFLAssetLog, Log, All);

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(KBFLWorldModuleLog, Log, All);

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(AssetDataSubsystemLog, Log, All);

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(ContentCDOHelperSubsystem, Log, All);

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(KBFLGameInstanceModuleLog, Log, All);

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(KBFLMenuModuleLog, Log, All);

KBFL_API DECLARE_LOG_CATEGORY_EXTERN(CustomizerSubsystem, Log, All);
