;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/KBFL/Content/Localization/KBFL
DestinationPath=Mods/GameFeatures/KBFL/Content/Localization/KBFL
ManifestName=KBFL.manifest
ArchiveName=KBFL.archive
ResourceName=KBFL.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de-DE
CulturesToGenerate=fr-FR
CulturesToGenerate=ko-KR
CulturesToGenerate=ru-RU
CulturesToGenerate=zh-TW

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

