;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/KBFL/Content/Localization/KBFL
DestinationPath=Mods/GameFeatures/KBFL/Content/Localization/KBFL
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de-DE
CulturesToGenerate=fr-FR
CulturesToGenerate=ko-KR
CulturesToGenerate=ru-RU
CulturesToGenerate=zh-TW
ManifestName=KBFL.manifest
ArchiveName=KBFL.archive
PortableObjectName=KBFL.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Unreal

