;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/KAPI/Content/Localization/KAPI
DestinationPath=Mods/GameFeatures/KAPI/Content/Localization/KAPI
ManifestName=KAPI.manifest
ArchiveName=KAPI.archive
ResourceName=KAPI.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
NativeCulture=en
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

